### ISSUE TITLE
Setup auto publishing of maven artifacts.

### ISSUE THREAD

**Issue by briandilley** [onflow/flow-jvm-sdk#19]
We'd like for the maven artifacts for both snapshots and releases be automatically deployed to maven central via sonatype.

The instructions for configuration are [here](https://github.com/onflow/flow-jvm-sdk/blob/main/.github/CUTTING-RELEASES.md#github-actions)

**Comment by psiemens** [comment]
This is configured now, and I moved the release instructions into the root of the repo: https://github.com/onflow/flow-jvm-sdk/blob/main/RELEASES.md
