### ISSUE TITLE
Access API Impl of getLatestBlock ignores sealed

### ISSUE THREAD

**Issue by Mrc0113** [onflow/flow-jvm-sdk#23]
### Problem
JVM implementation of Access API does not respect the `sealed` parameter in the `getLatestBlock` method. 

### Steps to Reproduce 

The code below does not return the latest sealed block due to the `sealed` param being ignored by the `getLatestBlock` impl 
``` java
	public FlowBlock getLatestBlock(boolean sealed) {
		return this.accessAPI.getLatestBlock(true);
	}
```
### Acceptance Criteria

The `sealed` param should be respected as defined in the docs. 
  
### Context

See AccessApiImpl below. I'm not a Kotlin developer, but it does not seem to use the `sealed` parameter: 
https://github.com/onflow/flow-jvm-sdk/blob/b35971112bea92a0ced347b71b26572d1afbd065/src/main/kotlin/org/onflow/sdk/impl/FlowAccessApiImpl.kt#L66-L72

**Comment by briandilley** [comment]
Good find, will address it.

**Comment by Mrc0113** [comment]
great, thanks @briandilley!

**Comment by briandilley** [comment]
fixed here: https://github.com/the-nft-company/flow-jvm-sdk/commit/72364c1ed30ca86a4c14efe16266ed8155fde2ec

**Comment by Mrc0113** [comment]
thanks @briandilley!
